version: "3.7"

services:
  server:
    image: drone/drone:2
    container_name: drone-server
    ports:
      - 80:80
      # ngrok >> 必須先跑起來 給外部溝通的 port
    restart: always
    volumes:
      - /Users/ansonjetthaisoft.com/test/drone:/data
    environment:
      # github app id
      DRONE_GITHUB_CLIENT_ID: "89b7aad0b3ca31b8b2b4"
      # github 金鑰
      DRONE_GITHUB_CLIENT_SECRET: "f28d3e3c0e056bb35e8fd9beec532593163c5b5a"
      # drone server 需要與 runner (client) 連接的金鑰 !!! 需要與 runner 設定一樣才找得到
      DRONE_RPC_SECRET: "super-duper-secret"
      DRONE_SERVER_HOST: "5e42-1-170-14-169.ngrok.io"
      DRONE_SERVER_PROTO: "http"

  app:
    image: drone/drone-runner-docker:1
    container_name: dorne-runner
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      DRONE_RPC_PROTO: "http"
      DRONE_RPC_HOST: "5e42-1-170-14-169.ngrok.io"
      # 與 drone server 連接的金鑰 
      DRONE_RPC_SECRET: "super-duper-secret"
      DRONE_RUNNER_CAPACITY: "1"
      DRONE_RUNNER_NAME: "my-first-runner"