version: "3.7"

services:
  app:
    image: portainer/portainer
    restart: always
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/ansonjetthaisoft.com/test/Portainer:/data